### PR TITLE
Fix missing configuration reference in API initializer

### PR DESCRIPTION
**Pull request by gerbal**
This change fixes using this library with the configuration initializer pattern documented in the configuration

### CODE REVIEW

**Comment by gerbal** [comment]
Prior to this change, values set by `BrazeRuby.configure` are never used. Instead the configuration is required to be passed at every invocation of  `BrazeRuby::API.new/3`. It is my assumption, that if the Braze API key and URL are set in configuration, we should not have to pass the api key and url as arguments to `Braze::API.new`. 

For example, prior to this change, the following usage is not valid

```ruby
BrazeRuby.configure do |config|
      config.rest_api_key = "test"
      config.rest_url =  "https://rest.iad-03.braze.com"
end

# why do I need to pass already-set configuration variable to instantiate the API?
> BrazeRuby::API.new()
ArgumentError: wrong number of arguments (given 0, expected 2..3)
```

**Comment by aganov** [comment]
@jonallured can we merge this? Thanks!

**Comment by jackewing** [comment]
@jonallured it would be wonderful if you could merge this or https://github.com/jonallured/braze_ruby/pull/59 - I'm sure there are many others using your gem to conform to the new unsubscribe rules.

**Comment by jonallured** [comment]
Closing this one in favor of #64 - thank you again to @gerbal for this PR and for all your patience. 😬

**Pull request closed without merging**
