### PR TITLE
Faraday middlewares

### PR DESCRIPTION
**Pull request by defkef**
Make Faraday middlewares available in the option hash to allow desired behavior, e.g. for instrumentation or raising errors when the API call failed.

### CODE REVIEW

**Comment by jonallured** [comment]
Hi @defkef thanks for the PR looks great! If you can update the CHANGELOG then I'm happy to merge. Looking to cut a release this week. 👍

**Comment by defkef** [comment]
> Hi @defkef thanks for the PR looks great! If you can update the CHANGELOG then I'm happy to merge. Looking to cut a release this week. 👍

Hi @jonallured, done

**Comment by jonallured** [comment]
Hey @defkef I just published a blog post inspired by this PR and wanted to let you know in case it's of interest to you!!

https://www.jonallured.com/posts/2024/11/17/tracing-objects-in-braze-ruby.html

**Comment by jonallured** [comment]
Released with [v0.11.0](https://github.com/jonallured/braze_ruby/blob/main/CHANGELOG.md#0110---2025-01-31) 🎉

**Pull request merged**
