### PR TITLE
Endpoint for 'remove email address from spam'

### PR DESCRIPTION
**Pull request by brrusselburg**
[Documentation](https://www.braze.com/docs/api/endpoints/email/post_remove_spam/#example-request)

Adding the endpoint that lets one remove a list of email addresses from Braze's spam list.

### CODE REVIEW

**Comment by jonallured** [comment]
Thanks @brrusselburg this looks legit but wasn't built on CircleCI due to #35 - I hope to address that and then maybe we can trigger this PR to build with a rebase? Will report back soon!

**Comment by jonallured** [comment]
Hey @brrusselburg can you rebase on latest main branch - that should cause CircleCI to build and verify this work. Thanks!

**Comment by jonallured** [comment]
Hey @brrusselburg I wanted to call out that you can run `bundle exec rake` on your local machine to simulate the CircleCI behavior. It'll first run standardrb and then rspec. I think you'll find that there are standardrb violations here and I think those can be fixed with `bundle exec standardrb --fix`. Hope that helps!!

**Comment by brrusselburg** [comment]
> Hey @brrusselburg I wanted to call out that you can run `bundle exec rake` on your local machine to simulate the CircleCI behavior. It'll first run standardrb and then rspec. I think you'll find that there are standardrb violations here and I think those can be fixed with `bundle exec standardrb --fix`. Hope that helps!!

Thank you! That helped with most of the lint issues. It looks like Circle CI is still not happy? When I run locally it's passing.

Screen Shot 2021-07-15 at 09 44 59

**Comment by jonallured** [comment]
Hi again @brrusselburg I took the liberty of cloning down your work, fixing the violations, rebasing and pushing to this PR - hope that's ok! It's back to green so I'm going to merge and cut a release with this work. Thanks again for contributing!! 🎉 🏆

**Comment by brrusselburg** [comment]
> Hi again @brrusselburg I took the liberty of cloning down your work, fixing the violations, rebasing and pushing to this PR - hope that's ok! It's back to green so I'm going to merge and cut a release with this work. Thanks again for contributing!! 🎉 🏆

Absolutely fine, thanks a ton!

**Pull request merged**
